In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/netflix_titles.csv")

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [3]:
df.shape

(8807, 12)

In [4]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [5]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [7]:
df_clean = df.copy()

In [8]:
text_columns = ["director", "cast", "country", "date_added", "rating", "duration"]

df_clean[text_columns] = df_clean[text_columns].fillna("Unknown")

In [9]:
df_clean.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [10]:
df_clean.duplicated().sum()

np.int64(0)

In [11]:
df_clean = df_clean.drop_duplicates()

In [12]:
for col in df_clean.select_dtypes(include="object").columns:
    df_clean[col] = df_clean[col].str.strip()

C:\Users\paulh\AppData\Local\Temp\ipykernel_5884\1854410094.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_clean.select_dtypes(include="object").columns:

In [13]:
df_clean["rag_text"] = (
    "Title: " + df_clean["title"] + "\n" +
    "Type: " + df_clean["type"] + "\n" +
    "Director: " + df_clean["director"] + "\n" +
    "Cast: " + df_clean["cast"] + "\n" +
    "Country: " + df_clean["country"] + "\n" +
    "Release year: " + df_clean["release_year"].astype(str) + "\n" +
    "Rating: " + df_clean["rating"] + "\n" +
    "Duration: " + df_clean["duration"] + "\n" +
    "Categories: " + df_clean["listed_in"] + "\n" +
    "Description: " + df_clean["description"]
)

df_clean[["title", "rag_text"]].head()

                   title                                           rag_text
0   Dick Johnson Is Dead  Title: Dick Johnson Is Dead\nType: Movie\nDire...
1          Blood & Water  Title: Blood & Water\nType: TV Show\nDirector:...
2              Ganglands  Title: Ganglands\nType: TV Show\nDirector: Jul...
3  Jailbirds New Orleans  Title: Jailbirds New Orleans\nType: TV Show\nD...
4           Kota Factory  Title: Kota Factory\nType: TV Show\nDirector: ...

In [14]:
df_clean.to_csv("../data/cleaned_data.csv", index=False)